### PR TITLE
Tidy up package

### LINKED ISSUE #3: Tidy up aspects of package configuration
+ [ ] Migrate `setup.cfg` to `pyproject.toml`.
+ [ ] Remove duplicate files (`napari-loadafm/{LICENSE,README.md,pyproject.tom}`).
+ [ ] Remove `_version.py` and `._version.py`.
+ [ ] Black target `py311` and `py312`
+ [ ] Apply recommendations from [Repo-Review - Scientific Python Development Guide](https://learn.scientific-python.org/development/guides/repo-review/)

All with a view to building and releasing to PyPI to make the package `pip install`able.

### PR DESCRIPTION
**Pull request by ns-rse**
Closes #3

+ [x] Removes `.DS_Store` files and excludes further by adding to `.gitignore`
+ [x] Moves `napari-loadafm/README.md` > `README.md`
+ [x] Removes duplicate `napari-loadafm/LICENSE` (which was MIT) in favour of top-level `LICENSE` which is GNU GPLv3.
+ [x] Removes duplicate `napari-loadafm/pyproject.toml` in favour of top-level `pyproject.toml`.
+ [x] Moves `setup.cfg` settings to top-level `pyproject.toml`
+ [x] Removes all `*_version.py` in favour of setting dynamically via `setuptools-scm` which is configured in `pyproject.toml` and ignores from future commits as its generated dynamically.
+ [x] Introduces `pre-commit` for linting the code (including with `pylint` and associated files )and Markdown (via `markdownlint-cli2` and associated configuration file). **NB** rules have been applied to code but not `README.md`.

One task has been left untouched and passed on to its own issue (see #7).

I've tested as far as possible by installing locally which completes without error but haven't tested whether the plugin actually works and can read the included `cat.spm` (which in due course as tests are written should be moved to `tests/resources/cat.spm`) as I've not yet read up on how to load plugins locally. Confusingly the entry point defined in `setup.cfg` (`napari.manifest`) points to `napari-loadafm = napari_topostats:napari.yaml` which doesn't exist. :thinking:

I think perhaps we need to think about and discuss how Napari plugins might be structured and whether we want one package `napari-TopoStats` with lots of plugins `napari-loadafm` / `napari-saveafm` / `napari-topostats-filter` / `napari-topostats-grains` / etc. or whether these should be individual packages.

### CODE REVIEW

**Comment by MaxGamill-Sheffield** [comment]
`napari.yaml` doesn't exist I assume because I've used the same `.gitignore` as TopoStats which ignores yaml files. I'll make a PR to add it now :) 

Then will test this branch with the Napari install

**Comment by MaxGamill-Sheffield** [comment]
Also with the moving of the `.spm` file to its own place, there's a certain way to make a "test file" available from within Napari which might be work looking into too.

**Comment by ns-rse** [comment]
I know pretty much zero about Napari plugin development and need to read up on how to structure these things so won't start moving things around just yet (how this fits into the overall Project RoadMap is important, its exciting to get new things working but still have lots that is already underway).

Need to read up on how `Manifest` work and reconcile that with entry points and `src` in the module path.

**Review by MaxGamill-Sheffield — APPROVED** [review]
Thanks for tidying this up Neil! 

Looks good and runs as expected (I just used my current napari env but re-pip installed this module) :)

There are a few additional bits of code which aren't used for our plugin but I thought I'd leave them incase we need to know how to do something and there is an example. We can get rid of them later after a second round of tidying when we're a bit more confident with Napari.

**Pull request merged**
